/**
 * Show My Artist page — high-contrast, single-screen, large-type view.
 * Designed to be shown to an artist across a table.
 */
import { useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { SkinSwatch } from '../components/SkinSwatch'
import UndertoneChip from '../components/UndertoneChip'
import TipList from '../components/TipList'

export default function ShowArtist() {
  const navigate = useNavigate()
  const location = useLocation()
  const data = location.state

  useEffect(() => {
    if (!data || !data.recommendation) {
      navigate('/scan', { replace: true })
    }
  }, [data, navigate])

  if (!data || !data.recommendation) return null

  const rec = data.recommendation
  const rangeMin = Math.min(data.monkLevel, data.monkAlt)
  const rangeMax = Math.max(data.monkLevel, data.monkAlt)

  return (
    <div className="min-h-screen bg-espresso text-ivory">
      {/* Back button */}
      <div className="p-4 no-print">
        <button
          onClick={() => navigate('/brief', { state: data })}
          className="flex items-center gap-1 text-sm text-ivory/60 hover:text-ivory cursor-pointer transition-colors"
        >
          <ArrowLeft size={16} />
          Back to Brief
        </button>
      </div>

      <div className="container-app max-w-md mx-auto pb-8 space-y-8">
        {/* Header */}
        <div className="text-center">
          <p className="text-xs uppercase tracking-widest text-marigold mb-2">Complexion Brief</p>
          <h1 className="text-2xl font-bold mb-4">For My Makeup Artist</h1>
        </div>

        {/* Skin profile — large */}
        <div className="flex items-center justify-center gap-6">
          <div className="flex items-center gap-2">
            <SkinSwatch level={rangeMin} size={56} selected />
            {rangeMin !== rangeMax && (
              <>
                <span className="text-ivory/40 text-lg">–</span>
                <SkinSwatch level={rangeMax} size={56} selected />
              </>
            )}
          </div>
          <div>
            <p className="text-2xl font-bold">
              Monk {rangeMin === rangeMax ? rangeMin : `${rangeMin}–${rangeMax}`}
            </p>
            <div className="mt-1">
              <UndertoneChip undertone={data.undertone} selected />
            </div>
          </div>
        </div>

        {/* Foundation note */}
        <div className="bg-ivory/10 rounded-xl p-5">
          <h2 className="text-lg font-semibold text-marigold mb-2">Foundation</h2>
          <p className="text-sm leading-relaxed text-ivory/80">{rec.foundation}</p>
          <p className="text-sm mt-2">
            <span className="font-medium text-marigold">Range:</span> {rec.shadeRange}
          </p>
        </div>

        {/* Must-do (top 5 from techniques + trial tips) */}
        <div>
          <h2 className="text-lg font-semibold text-marigold mb-3">Must-Do</h2>
          <TipList
            items={[
              'Test on jawline AND neck in natural light',
              'Use a flash test to check for white cast',
              ...rec.techniques.slice(0, 3),
            ]}
            type="do"
          />
        </div>

        {/* Avoid (top 3) */}
        <div>
          <h2 className="text-lg font-semibold text-marigold mb-3">Please Avoid</h2>
          <TipList items={rec.avoid.slice(0, 3)} type="avoid" />
        </div>

        {/* Call to action */}
        <p className="text-center text-sm text-ivory/50 italic">
          "Please test on jawline and neck in natural light."
        </p>

        {/* Attribution */}
        <p className="text-center text-xs text-ivory/30 mt-8">
          Generated by SkinSync · skinsync.vercel.app
        </p>
      </div>
    </div>
  )
}
